[package]
name = "rust_microservice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
futures = "0.3.30"
hyper = "1.1.0"
log = "0.4.20"
