[package]
name = "rs-find"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
fuzzy-matcher = "0.3.7"
glob = "0.3.1"
